#!/bin/bash
#   dht11-chip
#   Copyright (C) 2017  Vilppu Vuorinen <vilppu.jotain@gmail.com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

IIO_DIR="/sys/bus/iio/devices"

read_sensor() {
  T=$(cat $1/in_temp_input)
  if [ "$?" -ne 0 ]; then continue; fi
  H=$(cat $1/in_humidityrelative_input)
  if [ "$?" -ne 0 ]; then continue; fi

  echo "[$(TZ="Europe/Helsinki" date -Iseconds) - $(cat "${1}/name")]: T=$((${T} / 1000)).$((((${T} % 1000)+50)/100))C RH=$((${H} / 1000)).$((((${H} % 1000)+50)/100))%"
}

FOUND=0
for d in $IIO_DIR/iio\:device*; do
  if grep -q "dht11" "${d}/name" &> /dev/null; then
    FOUND=1
  fi
done

if [ $FOUND -eq 0 ]; then
  echo "No dht11 sensors found"
  exit 1
fi

while true; do

  for d in $IIO_DIR/iio\:device*; do
    if grep -q "dht11" "${d}/name"; then
      read_sensor "${d}"
    fi
  done

  sleep 2
done
