#!/bin/sh
# prerm script for dht11-chip
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
	rmmod dht11 &> /dev/null || true
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
